<a href="https://colab.research.google.com/github/sowmyaiyer/python_ds_adventures/blob/main/ISLP_LinRegLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#!pip install ISLP
import numpy as np
import pandas as pd
import matplotlib as mb

import statsmodels as sm





In [3]:
#### Chapter 2.4 exercises

# 7. KNN classifier
def euclidean(df, vec2) :
  if (df.shape[1]!= len(vec2)) :
    raise Exception("Inputs have to be the same length")
    return
  print ("nrows is ", df.shape[0])
  sum = np.zeros(df.shape[0], dtype = "float64")
  for i in range(df.shape[0]) :
    sum[i] = np.sqrt(
        np.sum(
            np.square(
                    np.subtract(df.iloc[i], vec2)
                    )
            )
        )
  return sum


#print("euclidean distance = ",  euclidean([2,1,0,1,5],[1,1,0,0,0.1]))



import numpy as np
df = pd.DataFrame({'Obs': ['Obs' + str(n) for n in range(6)],
                   'X1' : [0,2,0,0,-1,1],
                   'X2': [3,0,1,1,3,1],
                   'X3': [0,0,3,2,2,1],
                   'Y' : ['Red','Red','Red','Green','Green','Red']})



print("df is ", df)
df2 = df.set_index('Obs')
df2_sub = df2.iloc[0:5, 0:3]

print("df2_sub is \n", df2_sub)

k = 3
results_ind = np.argsort(euclidean(df2_sub, vec2 = [0,0,0]),)[range(k)]
results = np.sort(euclidean(df2_sub, vec2 = [1,1,1]),)[range(k)]


print("results_ind are \n", results_ind)
print("results are \n", results)
classes = df.loc[results_ind,'Y']

tabled = pd.crosstab(classes, 'Y')
print("wtf is tabled ", np.argmax(tabled.Y))
tabled.index[np.argmax(tabled.Y)]
#tabled.columns
#tabled



df is      Obs  X1  X2  X3      Y
0  Obs0   0   3   0    Red
1  Obs1   2   0   0    Red
2  Obs2   0   1   3    Red
3  Obs3   0   1   2  Green
4  Obs4  -1   3   2  Green
5  Obs5   1   1   1    Red
df2_sub is 
       X1  X2  X3
Obs             
Obs0   0   3   0
Obs1   2   0   0
Obs2   0   1   3
Obs3   0   1   2
Obs4  -1   3   2
nrows is  5
nrows is  5
results_ind are 
 [1 3 0]
results are 
 [1.41421356 1.73205081 2.23606798]
wtf is tabled  1


'Red'

In [ ]:
#### 2.4 ISLP exercise KNN classifier proper
# euclid function gets euclidean distance between each row of a dataframe and vec2
def euclid(df, vec2) :
  sum = np.zeros(df.shape[0], dtype = "float64")
  for i in range(df.shape[0]) :
    sum[i] = np.sqrt(
        np.sum(
            np.square(
                np.subtract([df.iloc[i]], vec2))
          ))

  return(sum)


test = pd.DataFrame([[1,1,1],[3,3,3]])
#test.iloc[1]
# just testing with toy example
print(np.subtract([test.iloc[i] for i in range(test.shape[0])], [0,0,0]))
print(euclid(test, [0,0,0]))

# create a matrix of 33 rows and 3 columns, from std normal dist
rng = np.random.default_rng()
mat_random = pd.DataFrame(rng.normal(size=99, loc=0, scale=1).reshape(33,3))
mat_random.columns = ['X' + str(n) for n in range(1,4)]
mat_random.columns
print("starting matrix is \n", mat_random)
mat_random['Obs'] = ['Obs' + str(n) for n in range(1,34)]
mat_random = mat_random.set_index('Obs')
label_rep = np.repeat(['Red','Green','Green'],repeats = 11)
label_rep
rng.shuffle(label_rep)


mat_random['label'] = label_rep

#label_random = np.repeat(['Red','Green'],repeats=10)

mat_random = pd.DataFrame(mat_random)
vec2 = [-1,1,0]
dist_results = euclid(mat_random.iloc[:,[0,1,2]], vec2)
dist_results_indexes_sorted = np.argsort(dist_results)

k = 5
top_k_labels = mat_random.iloc[dist_results_indexes_sorted[range(k)]]['label']
#closest_k_labels = mat_random[dist_results_indexes_sorted, 'label']
tab = pd.crosstab(top_k_labels, columns=0)
tab['prob'] = tab[0]/np.sum(tab[0])
print(dist_results)
print(tab)
print("For k = ", k, " assignment of ", vec2, "is" , tab.index[np.argmax(tab['prob'])], "with a prob of ", np.max(tab['prob']))
np.sum(mat_random['label'] == 'Red')
np.sum(mat_random['label'] == 'Green')

In [124]:
#### 3.6 Lab
#!pip install ISLP

import numpy as np
import pandas as pd
import matplotlib as mb

import statsmodels as sm
import sklearn

from ISLP import load_data
from ISLP.models import ModelSpec as MS
from ISLP.models import summarize
from ISLP.models import poly

Boston = load_data("Boston")


X = pd.DataFrame({'intercept': np.ones(Boston.shape[0]), 'lstat': Boston['lstat']})
y = Boston['medv']

model = sm.api.OLS(y, X)
results = model.fit()

sum_results = results.summary().tables[1]

df = pd.DataFrame(sum_results)
df.columns = df.iloc[0]
df = df.iloc[1:]


stsc = sklearn.preprocessing.StandardScaler()



test_indices = np.random.choice(Boston.shape[0], replace=False, size=20)
train_indices = np.setdiff1d(np.array(Boston.index),test_indices)
train = Boston.iloc[train_indices]
test = Boston.iloc[test_indices]

train_fit = pd.DataFrame(stsc.fit_transform(train[['lstat','medv']]))
print(train_fit.shape)
test_transform = pd.DataFrame(stsc.transform(test[['lstat','medv']]))
X = pd.DataFrame({'intercept': np.ones(train_fit.shape[0]), 'lstat': train_fit[0]})
y = train_fit[1]

model = sm.api.OLS(y,X)
results = model.fit()
predictions = results.get_prediction(exog = test_transform)
predictions.predicted_mean

(486, 2)


array([-0.19688114,  0.40470471,  0.67742364, -0.85461502,  0.21219724,
       -1.58453919, -0.04447939,  0.54908532,  0.28438754, -2.20216734,
       -0.01239481,  0.26032411,  0.46085273,  0.19615495,  0.90201569,
        0.2763664 , -0.03645825,  0.10792236,  0.46887387,  0.64533906])