<a href="https://colab.research.google.com/github/sowmyaiyer/python_ds_adventures/blob/main/ISLP_LinRegLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!pip install ISLP
import numpy as np
import pandas as pd
import matplotlib as mb

import statsmodels as sm

#from ISLP import load_data



In [5]:
#### Chapter 2.4 exercises

# 7. KNN classifier
def euclidean(df, vec2) :
  if (df.shape[1]!= len(vec2)) :
    raise Exception("Inputs have to be the same length")
    return
  print ("nrows is ", df.shape[0])
  sum = np.zeros(df.shape[0], dtype = "float64")
  for i in range(df.shape[0]) :
    sum[i] = np.sqrt(
        np.sum(
            np.square(
                    np.subtract(df.iloc[i], vec2)
                    )
            )
        )
  return sum


#print("euclidean distance = ",  euclidean([2,1,0,1,5],[1,1,0,0,0.1]))



import numpy as np
df = pd.DataFrame({'Obs': ['Obs' + str(n) for n in range(6)],
                   'X1' : [0,2,0,0,-1,1],
                   'X2': [3,0,1,1,3,1],
                   'X3': [0,0,3,2,2,1],
                   'Y' : ['Red','Red','Red','Green','Green','Red']})



print("df is ", df)
df2 = df.set_index('Obs')
df2_sub = df2.iloc[0:5, 0:3]

print("df2_sub is \n", df2_sub)

k = 3
results_ind = np.argsort(euclidean(df2_sub, vec2 = [0,0,0]),)[range(k)]
results = np.sort(euclidean(df2_sub, vec2 = [1,1,1]),)[range(k)]


print("results_ind are \n", results_ind)
print("results are \n", results)
classes = df.loc[results_ind,'Y']

tabled = pd.crosstab(classes, 'Y')
print("wtf is tabled ", np.argmax(tabled.Y))
tabled.index[np.argmax(tabled.Y)]
#tabled.columns
#tabled



df is      Obs  X1  X2  X3      Y
0  Obs0   0   3   0    Red
1  Obs1   2   0   0    Red
2  Obs2   0   1   3    Red
3  Obs3   0   1   2  Green
4  Obs4  -1   3   2  Green
5  Obs5   1   1   1    Red
df2_sub is 
       X1  X2  X3
Obs             
Obs0   0   3   0
Obs1   2   0   0
Obs2   0   1   3
Obs3   0   1   2
Obs4  -1   3   2
nrows is  5
nrows is  5
results_ind are 
 [1 3 0]
results are 
 [1.41421356 1.73205081 2.23606798]
wtf is tabled  1


'Red'

In [6]:
#### 2.4 ISLP exercises
# euclid function gets euclidean distance between each row of a dataframe and vec2
def euclid(df, vec2) :
  print(df.shape[0])
  return(
      np.sqrt(
          np.sum(
              np.square(
                  np.subtract([df.iloc[i] for i in range(df.shape[0])], vec2))
          )
      )
  )

test = pd.DataFrame([[1,1,1],[3,3,3]])
#test.iloc[1]
print(np.subtract([test.iloc[i] for i in range(test.shape[0])], [0,0,0]))
print(euclid(test, [0,0,0]))

rng = np.random.default_rng()
mat_random = pd.DataFrame(rng.normal(size=99, loc=0, scale=1).reshape(33,3))
mat_random.columns = ['X' + str(n) for n in range(1,4)]
mat_random.columns
mat_random
mat_random['Obs'] = ['Obs' + str(n) for n in range(1,34)]
mat_random = mat_random.set_index('Obs')
label_rep = np.repeat(['Red','Green','Red'],repeats = 11)
label_rep
rng.shuffle(label_rep)
label_rep

mat_random['label'] = label_rep

#label_random = np.repeat(['Red','Green'],repeats=10)

mat_random = pd.DataFrame(mat_random)
mat_random


[[1 1 1]
 [3 3 3]]
2
5.477225575051661


X1        X2        X3  label
Obs                                       
Obs1  -0.697987  3.000494 -0.157085    Red
Obs2  -0.712480 -0.161335 -0.482392    Red
Obs3  -1.467919  0.113567 -0.881480  Green
Obs4  -0.016640  0.617550 -1.153385    Red
Obs5  -0.195763  0.169060  1.081002  Green
Obs6  -0.763791  0.173475  0.282292  Green
Obs7  -0.574760 -0.892732  0.103390    Red
Obs8  -0.303616  0.792208 -0.525926    Red
Obs9  -0.271832 -0.738008  0.869799    Red
Obs10 -0.100787  1.424140 -0.157825    Red
Obs11  0.444013 -0.752243 -0.131604    Red
Obs12  0.989448  0.575916  1.085393    Red
Obs13  0.356039 -2.135954 -1.405901    Red
Obs14  0.194693 -0.525725  0.421903    Red
Obs15 -0.993771 -1.051200 -0.591222    Red
Obs16  0.162114 -0.795966 -1.484677  Green
Obs17  1.427980  1.518605 -1.241466    Red
Obs18  0.169418  0.030218  0.416046    Red
Obs19  1.132966  2.149423  0.204016    Red
Obs20  1.675576 -0.564643  1.359520    Red
Obs21  0.779195 -0.566733 -1.180278    Red
Obs22 -0.216491 -0.224355 -0.967569  Green
Obs23 -0.193121 -1.585397  0.996197  Green
Obs24 -0.664490 -0.606171  0.519635    Red
Obs25 -0.397729 -0.502497  1.096056  Green
Obs26  0.860341  0.595695  0.498737    Red
Obs27 -0.311414 -0.483467 -0.807729  Green
Obs28  0.175679 -1.053747 -0.227338  Green
Obs29 -0.132864 -0.912031 -0.083259    Red
Obs30 -0.466167  1.695306  0.429875    Red
Obs31  0.302935  0.867409  0.425561    Red
Obs32  2.382287 -0.780534 -0.861597  Green
Obs33  0.364044  0.297691 -0.547192  Green