<a href="https://colab.research.google.com/github/sowmyaiyer/python_ds_adventures/blob/main/ISLP_LinRegLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!pip install ISLP
import numpy as np
import pandas as pd
import matplotlib as mb

import statsmodels as sm

#from ISLP import load_data



In [5]:
#### Chapter 2.4 exercises

# 7. KNN classifier
def euclidean(df, vec2) :
  if (df.shape[1]!= len(vec2)) :
    raise Exception("Inputs have to be the same length")
    return
  print ("nrows is ", df.shape[0])
  sum = np.zeros(df.shape[0], dtype = "float64")
  for i in range(df.shape[0]) :
    sum[i] = np.sqrt(
        np.sum(
            np.square(
                    np.subtract(df.iloc[i], vec2)
                    )
            )
        )
  return sum


#print("euclidean distance = ",  euclidean([2,1,0,1,5],[1,1,0,0,0.1]))



import numpy as np
df = pd.DataFrame({'Obs': ['Obs' + str(n) for n in range(6)],
                   'X1' : [0,2,0,0,-1,1],
                   'X2': [3,0,1,1,3,1],
                   'X3': [0,0,3,2,2,1],
                   'Y' : ['Red','Red','Red','Green','Green','Red']})



print("df is ", df)
df2 = df.set_index('Obs')
df2_sub = df2.iloc[0:5, 0:3]

print("df2_sub is \n", df2_sub)

k = 3
results_ind = np.argsort(euclidean(df2_sub, vec2 = [0,0,0]),)[range(k)]
results = np.sort(euclidean(df2_sub, vec2 = [1,1,1]),)[range(k)]


print("results_ind are \n", results_ind)
print("results are \n", results)
classes = df.loc[results_ind,'Y']

tabled = pd.crosstab(classes, 'Y')
print("wtf is tabled ", np.argmax(tabled.Y))
tabled.index[np.argmax(tabled.Y)]
#tabled.columns
#tabled



df is      Obs  X1  X2  X3      Y
0  Obs0   0   3   0    Red
1  Obs1   2   0   0    Red
2  Obs2   0   1   3    Red
3  Obs3   0   1   2  Green
4  Obs4  -1   3   2  Green
5  Obs5   1   1   1    Red
df2_sub is 
       X1  X2  X3
Obs             
Obs0   0   3   0
Obs1   2   0   0
Obs2   0   1   3
Obs3   0   1   2
Obs4  -1   3   2
nrows is  5
nrows is  5
results_ind are 
 [1 3 0]
results are 
 [1.41421356 1.73205081 2.23606798]
wtf is tabled  1


'Red'

In [94]:
#### 2.4 ISLP exercise KNN classifier proper
# euclid function gets euclidean distance between each row of a dataframe and vec2
def euclid(df, vec2) :
  sum = np.zeros(df.shape[0], dtype = "float64")
  for i in range(df.shape[0]) :
    sum[i] = np.sqrt(
        np.sum(
            np.square(
                np.subtract([df.iloc[i]], vec2))
          ))

  return(sum)


test = pd.DataFrame([[1,1,1],[3,3,3]])
#test.iloc[1]
# just testing with toy example
print(np.subtract([test.iloc[i] for i in range(test.shape[0])], [0,0,0]))
print(euclid(test, [0,0,0]))

# create a matrix of 33 rows and 3 columns, from std normal dist
rng = np.random.default_rng()
mat_random = pd.DataFrame(rng.normal(size=99, loc=0, scale=1).reshape(33,3))
mat_random.columns = ['X' + str(n) for n in range(1,4)]
mat_random.columns
print("starting matrix is \n", mat_random)
mat_random['Obs'] = ['Obs' + str(n) for n in range(1,34)]
mat_random = mat_random.set_index('Obs')
label_rep = np.repeat(['Red','Green','Green'],repeats = 11)
label_rep
rng.shuffle(label_rep)


mat_random['label'] = label_rep

#label_random = np.repeat(['Red','Green'],repeats=10)

mat_random = pd.DataFrame(mat_random)
vec2 = [-1,1,0]
dist_results = euclid(mat_random.iloc[:,[0,1,2]], vec2)
dist_results_indexes_sorted = np.argsort(dist_results)

k = 5
top_k_labels = mat_random.iloc[dist_results_indexes_sorted[range(k)]]['label']
#closest_k_labels = mat_random[dist_results_indexes_sorted, 'label']
tab = pd.crosstab(top_k_labels, columns=0)
tab['prob'] = tab[0]/np.sum(tab[0])
print(dist_results)
print(tab)
print("For k = ", k, " assignment of ", vec2, "is" , tab.index[np.argmax(tab['prob'])], "with a prob of ", np.max(tab['prob']))
np.sum(mat_random['label'] == 'Red')
np.sum(mat_random['label'] == 'Green')

[[1 1 1]
 [3 3 3]]
[1.73205081 5.19615242]
starting matrix is 
           X1        X2        X3
0   0.257422 -0.146260 -0.268118
1  -0.163245 -0.489493  0.488946
2   1.853189  0.201341  0.949198
3  -1.112501  1.112508 -0.386813
4   2.330019 -0.363570 -0.006290
5   0.314487 -0.618103 -0.073228
6   1.840721  0.808933 -1.261121
7  -0.504799  0.994807  0.708031
8  -0.198730 -1.814776 -0.444681
9   0.415120  1.871883  2.226400
10  2.444555 -0.047143 -0.660720
11  0.834170  0.006960 -0.997551
12 -1.181191 -1.597242 -0.002522
13  1.633594  0.176963  0.202525
14 -0.780199 -0.109563  0.621380
15  0.912339  0.555838  0.029859
16 -2.193282 -1.341733  0.269993
17  1.117571 -0.090315  0.426226
18 -0.607682 -0.829252  0.540503
19  0.312887 -0.027083  0.381357
20 -0.272928 -0.234538  0.481054
21  0.816661  0.034588  0.320755
22 -1.681112  1.601354 -1.062038
23  1.233941  1.137735 -1.015362
24 -1.210853 -0.888417  0.566252
25  0.076983 -0.666490 -0.628178
26  0.886290  0.711192 -1.714456
27 -0.508307

22